#TODO add code to find java binary.
JAVA=java

RHINOPATHJAR=../tools/rhino1_7R2/js.jar
RHINO=$(JAVA) -jar $(RHINOPATHJAR)

# TODO add target to run $(RHINO) ../tools/jslint/jslint.js $(SOURCES)
#jslint:
#	$(RHINO) ../tools/jslint/jslint.js

